"use client";
import {useCallback,useEffect,useMemo,useState} from "react";
import {createClient,type Session} from "@supabase/supabase-js";
import "../homologacao.css";

const supabase=createClient(process.env.NEXT_PUBLIC_SUPABASE_URL||"https://zyekgimmyosbxawvllvs.supabase.co",process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY||"sb_publishable_QFMzIAr9q6jeM8o0yDKr7A_A5KZU9Pd");
const logo="https://raw.githubusercontent.com/lucviscard-prog/qualific.estetic/main/public/logo-qualificar-correta.webp";
const localDay=()=>{const d=new Date();return [d.getFullYear(),String(d.getMonth()+1).padStart(2,"0"),String(d.getDate()).padStart(2,"0")].join("-")};
const niceDate=(v:string)=>new Date(v+"T12:00:00").toLocaleDateString("pt-BR");
const time=(v:string|null|undefined)=>v?v.slice(0,5):"--:--";
const state=(v:string)=>({REQUESTED:"Solicitado",CONFIRMED:"Confirmado",CUSTOMER_ARRIVED:"Check-in",IN_SERVICE:"Em serviço",AWAITING_PICKUP:"Pronto",COMPLETED:"Concluído",CANCELLED:"Cancelado",NO_SHOW:"Não compareceu",RESCHEDULED:"Reagendado"} as Record<string,string>)[v]||v;

type StaffProfile={full_name:string;role:string};
type Attendance={id:string;status:string;km_entry:number;km_exit:number|null;inspection_completed_at:string|null;checkin_at:string|null;service_started_at:string|null;service_finished_at:string|null;delivered_at:string|null;dirt_level:string|null};
type Booking={id:string;booking_date:string;start_time:string;end_time:string;status:string;delivery_mode:string;observations:string|null;final_price:number|null;customer:{full_name:string;whatsapp:string|null}|null;vehicle:{make:string;model:string;plate:string;color:string|null}|null;items:{historical_name:string;historical_duration_minutes:number;quantity:number}[];attendance:Attendance[]};
type Inspection={attendance_id:string;km_entry:number;dirt_level:string|null;belongings_notes:string|null;preexisting_damage_notes:string|null;inspection_completed_at:string|null;checklist:{id:string;item:string;completed:boolean;observation:string|null}[];special_care:{type:string;status:string;product_used:string|null;maintenance_notes:string|null}[]};
type Photo={id:string;type:string;category:string;storage_path:string;description:string|null;display_order:number;url?:string};

export default function OperacaoReal(){
 const [session,setSession]=useState<Session|null>(null),[checking,setChecking]=useState(true),[authorized,setAuthorized]=useState(false),[profile,setProfile]=useState<StaffProfile|null>(null);
 const [day,setDay]=useState(localDay()),[bookings,setBookings]=useState<Booking[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState(""),[notice,setNotice]=useState("");
 const [selected,setSelected]=useState<Booking|null>(null),[panel,setPanel]=useState<"checkin"|"inspection"|"photos"|"delivery"|null>(null);
 const [kmEntry,setKmEntry]=useState(""),[entryNotes,setEntryNotes]=useState(""),[kmExit,setKmExit]=useState(""),[exitNotes,setExitNotes]=useState("");
 const [inspection,setInspection]=useState<Inspection|null>(null),[dirt,setDirt]=useState("MEDIUM"),[belongings,setBelongings]=useState(""),[damages,setDamages]=useState("");
 const [photos,setPhotos]=useState<Photo[]>([]),[photoType,setPhotoType]=useState("BEFORE"),[photoCategory,setPhotoCategory]=useState("FRONT"),[photoDescription,setPhotoDescription]=useState(""),[photoFile,setPhotoFile]=useState<File|null>(null);

 const verify=useCallback(async()=>{
  const user=await supabase.auth.getUser();if(!user.data.user){setAuthorized(false);return}
  const staff=await supabase.rpc("is_staff");if(staff.error||staff.data!==true){setAuthorized(false);return}
  const p=await supabase.from("profiles").select("full_name,role").eq("id",user.data.user.id).maybeSingle();
  if(p.data){setProfile(p.data as StaffProfile);setAuthorized(true)}
 },[]);

 const load=useCallback(async(target=day)=>{
  setBusy(true);setError("");setNotice("");
  const r=await supabase.from("bookings").select("id,booking_date,start_time,end_time,status,delivery_mode,observations,final_price,customer:customers(full_name,whatsapp),vehicle:vehicles(make,model,plate,color),items:booking_items(historical_name,historical_duration_minutes,quantity),attendance:attendances(id,status,km_entry,km_exit,inspection_completed_at,checkin_at,service_started_at,service_finished_at,delivered_at,dirt_level)").eq("booking_date",target).order("start_time");
  if(r.error)setError(r.error.message);else setBookings((r.data||[]) as unknown as Booking[]);
  setBusy(false);
 },[day]);

 useEffect(()=>{let live=true;supabase.auth.getSession().then(async({data})=>{if(!live)return;setSession(data.session);setChecking(false);if(data.session){await verify();}});const {data:sub}=supabase.auth.onAuthStateChange((_e,s)=>{setSession(s);if(s)window.setTimeout(()=>void verify(),0);else{setAuthorized(false);setProfile(null)}});return()=>{live=false;sub.subscription.unsubscribe()}},[verify]);
 useEffect(()=>{if(authorized)void load(day)},[authorized,day,load]);

 const counts=useMemo(()=>({
  total:bookings.length,
  waiting:bookings.filter(b=>["REQUESTED","CONFIRMED","CUSTOMER_ARRIVED"].includes(b.status)).length,
  working:bookings.filter(b=>b.status==="IN_SERVICE").length,
  ready:bookings.filter(b=>b.status==="AWAITING_PICKUP").length,
  done:bookings.filter(b=>b.status==="COMPLETED").length
 }),[bookings]);

 async function setStatus(id:string,status:string){setBusy(true);setError("");const r=await supabase.from("bookings").update({status}).eq("id",id);if(r.error)setError(r.error.message);else{setNotice("Status atualizado.");await load(day)}setBusy(false)}
 function open(b:Booking,p:typeof panel){setSelected(b);setPanel(p);setError("");setNotice("");if(p==="inspection")void loadInspection(b);if(p==="photos")void loadPhotos(b);if(p==="delivery"){const a=b.attendance?.[0];setKmExit(a?.km_exit?String(a.km_exit):"");setExitNotes("")}}
 async function doCheckin(){if(!selected||!kmEntry)return;setBusy(true);setError("");const r=await supabase.rpc("staff_checkin_booking",{p_booking_id:selected.id,p_km_entry:Number(kmEntry),p_entry_notes:entryNotes.trim()||null});if(r.error)setError(r.error.message);else{setPanel(null);setSelected(null);setKmEntry("");setEntryNotes("");setNotice("Check-in registrado.");await load(day)}setBusy(false)}
 async function loadInspection(b:Booking){setBusy(true);const r=await supabase.rpc("staff_get_inspection",{p_booking_id:b.id});if(r.error){setError(r.error.message)}else{const row=(r.data||[])[0] as Inspection|undefined;if(row){setInspection(row);setDirt(row.dirt_level||"MEDIUM");setBelongings(row.belongings_notes||"");setDamages(row.preexisting_damage_notes||"")}}setBusy(false)}
 function toggleItem(id:string){setInspection(v=>v?{...v,checklist:v.checklist.map(x=>x.id===id?{...x,completed:!x.completed}:x)}:v)}
 async function saveInspection(){if(!selected||!inspection)return;setBusy(true);setError("");const r=await supabase.rpc("staff_save_inspection",{p_booking_id:selected.id,p_dirt_level:dirt,p_belongings_notes:belongings.trim()||null,p_damage_notes:damages.trim()||null,p_checklist:inspection.checklist});if(r.error)setError(r.error.message);else{setNotice("Vistoria salva.");await loadInspection(selected);await load(day)}setBusy(false)}
 async function startService(b:Booking){setBusy(true);setError("");const r=await supabase.rpc("staff_start_service",{p_booking_id:b.id});if(r.error)setError(r.error.message);else{setNotice("Atendimento iniciado.");await load(day)}setBusy(false)}
 async function finishService(b:Booking){setBusy(true);setError("");const r=await supabase.rpc("staff_finish_service",{p_booking_id:b.id});if(r.error)setError(r.error.message);else{setNotice("Veículo marcado como pronto para retirada.");await load(day)}setBusy(false)}
 async function complete(){if(!selected||!kmExit)return;setBusy(true);setError("");const r=await supabase.rpc("staff_complete_attendance",{p_booking_id:selected.id,p_km_exit:Number(kmExit),p_exit_notes:exitNotes.trim()||null});if(r.error)setError(r.error.message);else{setPanel(null);setSelected(null);setNotice("Entrega concluída.");await load(day)}setBusy(false)}
 async function loadPhotos(b:Booking){setBusy(true);setPhotos([]);const r=await supabase.rpc("staff_get_attendance_photos",{p_booking_id:b.id});if(r.error){setError(r.error.message);setBusy(false);return}const rows=(r.data||[]) as Photo[];const signed=await Promise.all(rows.map(async p=>{const s=await supabase.storage.from("attendance-photos").createSignedUrl(p.storage_path,3600);return {...p,url:s.data?.signedUrl||""}}));setPhotos(signed);setBusy(false)}
 async function uploadPhoto(){if(!selected||!photoFile)return;setBusy(true);setError("");const safe=photoFile.name.replace(/[^a-zA-Z0-9._-]/g,"-");const path=`${selected.id}/${Date.now()}-${photoType.toLowerCase()}-${photoCategory.toLowerCase()}-${safe}`;const up=await supabase.storage.from("attendance-photos").upload(path,photoFile,{upsert:false,contentType:photoFile.type||undefined});if(up.error){setError(up.error.message);setBusy(false);return}const db=await supabase.rpc("staff_add_attendance_photo",{p_booking_id:selected.id,p_type:photoType,p_category:photoCategory,p_storage_path:path,p_description:photoDescription.trim()||null});if(db.error){await supabase.storage.from("attendance-photos").remove([path]);setError(db.error.message)}else{setPhotoFile(null);setPhotoDescription("");setNotice("Foto adicionada ao prontuário.");await loadPhotos(selected)}setBusy(false)}
 async function logout(){await supabase.auth.signOut();setAuthorized(false);setSession(null)}

 if(checking)return <main className="hv-packageAuth">Verificando acesso da equipe...</main>;
 if(!session)return <main className="hv-packageAuth"><section className="hv-panel"><img className="hv-manageLogo" src={logo} alt="Qualificar"/><h2>Central operacional</h2><p>Entre com a conta de equipe já cadastrada no Qualific.Estetic.</p><a className="hv-button" href="/">Entrar no sistema</a><a className="hv-outline" href="/homologacao">Voltar à homologação</a></section></main>;
 if(!authorized)return <main className="hv-packageAuth"><section className="hv-panel"><img className="hv-manageLogo" src={logo} alt="Qualificar"/><h2>Acesso restrito</h2><p>Esta área é exclusiva para ADMIN, MANAGER, RECEPTION ou PROFESSIONAL.</p><button className="hv-outline" onClick={logout}>Sair</button></section></main>;

 return <main className="hv-manager hv-ops"><div className="hv-managerTop"><a href="/homologacao">← Homologação geral</a><img src={logo} alt="Qualificar"/><div className="hv-opsIdentity"><span>{profile?.full_name}</span><small>{profile?.role}</small></div></div><div className="hv-managerBody">
  <div className="hv-heading"><div><span className="hv-overline">OPERAÇÃO CONECTADA · DADOS REAIS</span><h1>Central do Box 01.</h1><p>Agenda, check-in, vistoria, registros fotográficos e entrega em uma única esteira operacional.</p></div><div className="hv-opsDay"><label>Dia<input type="date" value={day} onChange={e=>setDay(e.target.value)}/></label><button className="hv-outline" disabled={busy} onClick={()=>void load(day)}>Atualizar</button></div></div>
  {notice&&<div className="hv-info" role="status">{notice}</div>}{error&&<div className="hv-realError" role="alert">{error}</div>}
  <div className="hv-opsStats"><div><span>Total</span><strong>{counts.total}</strong></div><div><span>Aguardando</span><strong>{counts.waiting}</strong></div><div><span>Em serviço</span><strong>{counts.working}</strong></div><div><span>Prontos</span><strong>{counts.ready}</strong></div><div><span>Concluídos</span><strong>{counts.done}</strong></div></div>
  <section className="hv-panel"><div className="hv-panelHead"><h3>Agenda de {niceDate(day)}</h3><small>{busy?"Sincronizando...":"Supabase em tempo real sob demanda"}</small></div><div className="hv-opsTimeline">{bookings.map(b=>{const a=b.attendance?.[0];const names=b.items?.map(x=>x.historical_name).join(" · ");return <article className="hv-opsCard" key={b.id}><div className="hv-opsTime"><b>{time(b.start_time)}</b><span>{time(b.end_time)}</span></div><div className="hv-opsCore"><div className="hv-opsTags"><span className="hv-pill gold">{state(b.status)}</span>{a?.inspection_completed_at&&<span className="hv-pill green">Vistoria ✓</span>}</div><h3>{b.vehicle?.make} {b.vehicle?.model}</h3><p>{b.vehicle?.plate||"Sem placa"} · {b.customer?.full_name||"Cliente"} · {b.customer?.whatsapp||"Sem WhatsApp"}</p><small>{names||"Serviço não identificado"}{b.observations?" · "+b.observations:""}</small>{a&&<div className="hv-opsTrace"><span>KM {a.km_entry.toLocaleString("pt-BR")}</span>{a.checkin_at&&<span>Entrada ✓</span>}{a.service_started_at&&<span>Início ✓</span>}{a.service_finished_at&&<span>Finalizado ✓</span>}{a.delivered_at&&<span>Entrega ✓</span>}</div>}</div><div className="hv-opsActions">
   {b.status==="REQUESTED"&&<button className="hv-button" onClick={()=>void setStatus(b.id,"CONFIRMED")}>Confirmar</button>}
   {b.status==="CONFIRMED"&&<button className="hv-button" onClick={()=>{setKmEntry("");setEntryNotes("");open(b,"checkin")}}>Check-in</button>}
   {b.status==="CUSTOMER_ARRIVED"&&<><button className="hv-outline" onClick={()=>open(b,"inspection")}>Vistoria</button><button className="hv-outline" onClick={()=>open(b,"photos")}>Fotos</button><button className="hv-button" disabled={!a?.inspection_completed_at} title={!a?.inspection_completed_at?"Conclua a vistoria antes de iniciar":""} onClick={()=>void startService(b)}>Iniciar</button></>}
   {b.status==="IN_SERVICE"&&<><button className="hv-outline" onClick={()=>open(b,"inspection")}>Vistoria</button><button className="hv-outline" onClick={()=>open(b,"photos")}>Fotos</button><button className="hv-button" onClick={()=>void finishService(b)}>Marcar pronto</button></>}
   {b.status==="AWAITING_PICKUP"&&<><button className="hv-outline" onClick={()=>open(b,"photos")}>Fotos</button><button className="hv-button" onClick={()=>open(b,"delivery")}>Entregar</button></>}
   {b.status==="COMPLETED"&&<button className="hv-outline" onClick={()=>open(b,"photos")}>Ver registros</button>}
  </div></article>})}{!bookings.length&&!busy&&<div className="hv-empty">Nenhum atendimento registrado para este dia.</div>}</div></section>
  <footer className="hv-footer"><span>QUALIFIC.ESTETIC · OPERAÇÃO CONECTADA</span><p>Esta área grava dados reais. Use apenas com contas da equipe e atendimentos de teste controlados.</p><a href="/homologacao">Voltar à demonstração ↗</a></footer>
 </div>

 {panel==="checkin"&&selected&&<div className="hv-opModal"><section className="hv-panel hv-opDialog"><div className="hv-panelHead"><div><span className="hv-overline">CHECK-IN</span><h3>{selected.vehicle?.make} {selected.vehicle?.model}</h3></div><button className="hv-opClose" onClick={()=>setPanel(null)}>×</button></div><label className="hv-blockLabel">Quilometragem de entrada<input type="number" min="0" step="1" value={kmEntry} onChange={e=>setKmEntry(e.target.value)} autoFocus/></label><label className="hv-blockLabel">Observações<textarea value={entryNotes} onChange={e=>setEntryNotes(e.target.value)} placeholder="Avarias, objetos, condição geral..."/></label><button className="hv-button wide" disabled={!kmEntry||busy} onClick={()=>void doCheckin()}>{busy?"Registrando...":"Confirmar entrada"}</button></section></div>}

 {panel==="inspection"&&selected&&<div className="hv-opModal"><section className="hv-panel hv-opDialog hv-opWide"><div className="hv-panelHead"><div><span className="hv-overline">VISTORIA INICIAL</span><h3>{selected.vehicle?.make} {selected.vehicle?.model}</h3></div><button className="hv-opClose" onClick={()=>setPanel(null)}>×</button></div>{inspection?<><div className="hv-twoFields"><label className="hv-blockLabel">Nível de sujeira<select value={dirt} onChange={e=>setDirt(e.target.value)}><option value="LIGHT">Leve</option><option value="MEDIUM">Média</option><option value="HEAVY">Pesada</option><option value="EXTREME">Extrema</option></select></label><div className="hv-line"><span>KM de entrada</span><b>{inspection.km_entry.toLocaleString("pt-BR")}</b></div></div>{inspection.special_care?.length>0&&<div className="hv-careAlert"><b>⚠ Cuidados especiais do veículo</b>{inspection.special_care.map((x,i)=><p key={i}>{x.type} · {x.status}{x.product_used?" · "+x.product_used:""}</p>)}</div>}<h4>Checklist visual</h4><div className="hv-opChecklist">{inspection.checklist.map(x=><label key={x.id} className={x.completed?"checked":""}><input type="checkbox" checked={x.completed} onChange={()=>toggleItem(x.id)}/><span>{x.item}</span></label>)}</div><label className="hv-blockLabel">Pertences / porta-malas<textarea value={belongings} onChange={e=>setBelongings(e.target.value)}/></label><label className="hv-blockLabel">Danos preexistentes<textarea value={damages} onChange={e=>setDamages(e.target.value)}/></label><button className="hv-button wide" disabled={busy} onClick={()=>void saveInspection()}>{busy?"Salvando...":"Salvar vistoria"}</button></>:<div className="hv-empty">{busy?"Carregando vistoria...":"Vistoria indisponível."}</div>}</section></div>}

 {panel==="photos"&&selected&&<div className="hv-opModal"><section className="hv-panel hv-opDialog hv-opWide"><div className="hv-panelHead"><div><span className="hv-overline">REGISTRO FOTOGRÁFICO</span><h3>{selected.vehicle?.make} {selected.vehicle?.model}</h3></div><button className="hv-opClose" onClick={()=>setPanel(null)}>×</button></div><div className="hv-photoForm"><label>Momento<select value={photoType} onChange={e=>setPhotoType(e.target.value)}><option value="BEFORE">Antes</option><option value="AFTER">Depois</option></select></label><label>Ângulo<select value={photoCategory} onChange={e=>setPhotoCategory(e.target.value)}><option value="FRONT">Frente</option><option value="REAR">Traseira</option><option value="LEFT">Lateral esquerda</option><option value="RIGHT">Lateral direita</option><option value="INTERIOR">Interior</option><option value="DETAIL">Detalhe</option><option value="DAMAGE">Avaria</option></select></label><label>Foto<input type="file" accept="image/*" onChange={e=>setPhotoFile(e.target.files?.[0]||null)}/></label><label>Descrição<input value={photoDescription} onChange={e=>setPhotoDescription(e.target.value)} placeholder="Opcional"/></label></div><button className="hv-button" disabled={!photoFile||busy} onClick={()=>void uploadPhoto()}>{busy?"Enviando...":"Adicionar ao prontuário"}</button><div className="hv-opPhotos">{photos.map(p=><figure key={p.id}>{p.url?<a href={p.url} target="_blank" rel="noreferrer"><img src={p.url} alt={p.category}/></a>:<div className="hv-empty">Sem prévia</div>}<figcaption>{p.type==="BEFORE"?"Antes":"Depois"} · {p.category}{p.description?" · "+p.description:""}</figcaption></figure>)}</div>{!photos.length&&!busy&&<div className="hv-empty">Nenhuma foto registrada neste atendimento.</div>}</section></div>}

 {panel==="delivery"&&selected&&<div className="hv-opModal"><section className="hv-panel hv-opDialog"><div className="hv-panelHead"><div><span className="hv-overline">ENTREGA DO VEÍCULO</span><h3>{selected.vehicle?.make} {selected.vehicle?.model}</h3></div><button className="hv-opClose" onClick={()=>setPanel(null)}>×</button></div><label className="hv-blockLabel">Quilometragem de saída<input type="number" min={selected.attendance?.[0]?.km_entry||0} step="1" value={kmExit} onChange={e=>setKmExit(e.target.value)}/></label><label className="hv-blockLabel">Observações de entrega<textarea value={exitNotes} onChange={e=>setExitNotes(e.target.value)} placeholder="Condição da entrega, orientações ao cliente..."/></label><button className="hv-button wide" disabled={!kmExit||busy} onClick={()=>void complete()}>{busy?"Concluindo...":"Concluir e entregar"}</button></section></div>}
 </main>;
}
