"use client";
import {useCallback,useEffect,useMemo,useState} from "react";
import {createClient,type Session} from "@supabase/supabase-js";
import "../homologacao.css";
const supabase=createClient(process.env.NEXT_PUBLIC_SUPABASE_URL||"https://zyekgimmyosbxawvllvs.supabase.co",process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY||"sb_publishable_QFMzIAr9q6jeM8o0yDKr7A_A5KZU9Pd");
const logo="https://raw.githubusercontent.com/lucviscard-prog/qualific.estetic/main/public/logo-qualificar-correta.webp";
type Car={id:string;make:string;model:string;year:number;color:string;plate:string;category:string;observations:string|null};
type Service={id:string;name:string;description:string|null;duration_minutes:number;requires_evaluation:boolean;allows_online_booking:boolean};
type Package={id:string;name:string;description:string|null};
type Booking={id:string;vehicle_id:string;booking_date:string;start_time:string;status:string;delivery_mode:string};
type Photo={id:string;type:string;category:string;storage_path:string;description:string|null;url?:string};
type RecordItem={id:string;booking_date:string;start_time:string;status:string;services:{name:string;quantity:number}[];attendance:null|{km_entry:number;km_exit:number|null;inspection_completed_at:string|null};photos:Photo[]};
type RecordData={vehicle:Car;special_care:{type:string;status:string;product_used:string|null;maintenance_notes:string|null}[];history:RecordItem[]};
type Quote={item_name:string;base_price:number;duration_minutes:number};
const money=(v:number)=>new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(Number(v));
const stateName=(v:string)=>({REQUESTED:"Solicitado",CONFIRMED:"Confirmado",CUSTOMER_ARRIVED:"Check-in",IN_SERVICE:"Em serviço",AWAITING_PICKUP:"Pronto para entrega",COMPLETED:"Concluído",CANCELLED:"Cancelado",NO_SHOW:"Não compareceu",RESCHEDULED:"Reagendado"} as Record<string,string>)[v]||v;
const niceDate=(v:string)=>v.split("-").reverse().join("/");
type Tab="resumo"|"garagem"|"agendar"|"historico"|"catalogo"|"perfil";
export default function ClienteReal(){
 const [session,setSession]=useState<Session|null>(null),[checking,setChecking]=useState(true),[busy,setBusy]=useState(false),[tab,setTab]=useState<Tab>("resumo"),[error,setError]=useState(""),[notice,setNotice]=useState("");
 const [email,setEmail]=useState(""),[password,setPassword]=useState(""),[customer,setCustomer]=useState<{id:string;full_name:string;whatsapp:string;email:string}|null>(null);
 const [cars,setCars]=useState<Car[]>([]),[services,setServices]=useState<Service[]>([]),[packages,setPackages]=useState<Package[]>([]),[bookings,setBookings]=useState<Booking[]>([]);
 const [vehicleId,setVehicleId]=useState(""),[serviceId,setServiceId]=useState(""),[day,setDay]=useState(""),[slots,setSlots]=useState<{start_time:string;end_time:string}[]>([]),[slot,setSlot]=useState(""),[quote,setQuote]=useState<Quote|null>(null);
 const [record,setRecord]=useState<RecordData|null>(null),[recordLoading,setRecordLoading]=useState(false),[delivery,setDelivery]=useState("CUSTOMER_BRINGS"),[notes,setNotes]=useState("");
 const [register,setRegister]=useState(false),[newCar,setNewCar]=useState({make:"",model:"",year:String(new Date().getFullYear()),color:"",plate:"",category:"HATCH",observations:""});
 const chosen=cars.find(v=>v.id===vehicleId)||null;
 const load=useCallback(async()=>{
  setBusy(true);setError("");
  const u=await supabase.auth.getUser();if(!u.data.user){setBusy(false);return}
  const c=await supabase.from("customers").select("id,full_name,whatsapp,email").eq("profile_id",u.data.user.id).maybeSingle();
  if(c.error){setError(c.error.message);setBusy(false);return}
  if(!c.data){setError("Não encontramos o cadastro de cliente vinculado a esta conta. Entre em contato com a recepção.");setBusy(false);return}
  setCustomer(c.data);
  const [v,s,p,b]=await Promise.all([
   supabase.from("vehicles").select("id,make,model,year,color,plate,category,observations").eq("customer_id",c.data.id).eq("active",true).order("created_at"),
   supabase.from("services").select("id,name,description,duration_minutes,requires_evaluation,allows_online_booking").eq("active",true).eq("allows_online_booking",true).order("name"),
   supabase.from("packages").select("id,name,description").eq("active",true).order("name"),
   supabase.from("bookings").select("id,vehicle_id,booking_date,start_time,status,delivery_mode").eq("customer_id",c.data.id).order("booking_date",{ascending:false}).order("start_time",{ascending:false}).limit(100)
  ]);
  const err=v.error||s.error||p.error||b.error;if(err)setError(err.message);
  setCars(v.data||[]);setServices(s.data||[]);setPackages(p.data||[]);setBookings(b.data||[]);
  setVehicleId(old=>(v.data||[]).some(x=>x.id===old)?old:v.data?.[0]?.id||"");
  setBusy(false);
 },[]);
 useEffect(()=>{let live=true;supabase.auth.getSession().then(({data})=>{if(!live)return;setSession(data.session);setChecking(false);if(data.session)void load()});const {data:subscription}=supabase.auth.onAuthStateChange((_evt,s)=>{setSession(s);if(s)window.setTimeout(()=>void load(),0);else{setCustomer(null);setCars([]);setBookings([]);setRecord(null)}});return()=>{live=false;subscription.subscription.unsubscribe()}},[load]);
 useEffect(()=>{setQuote(null);setSlots([]);setSlot("")},[vehicleId,serviceId,day]);
 const refreshRecord=useCallback(async(id:string)=>{setRecord(null);if(!id)return;setRecordLoading(true);setError("");const r=await supabase.rpc("customer_vehicle_prontuario",{p_vehicle_id:id});if(r.error){setError(r.error.message);setRecordLoading(false);return}const d=r.data as RecordData|null;if(d){const history=await Promise.all((d.history||[]).map(async(b:RecordItem)=>({...b,photos:await Promise.all((b.photos||[]).map(async(p:Photo)=>{const signed=await supabase.storage.from("attendance-photos").createSignedUrl(p.storage_path,3600);return {...p,url:signed.data?.signedUrl||""}}))})));setRecord({...d,history})}setRecordLoading(false)},[]);
 useEffect(()=>{if(tab==="historico"&&vehicleId)void refreshRecord(vehicleId)},[tab,vehicleId,refreshRecord]);
 async function login(e:React.FormEvent){e.preventDefault();setBusy(true);setError("");const r=await supabase.auth.signInWithPassword({email,password});if(r.error)setError(r.error.message);setBusy(false)}
 async function logout(){await supabase.auth.signOut();setSession(null);setCustomer(null);setTab("resumo")}
 async function getQuote(){if(!vehicleId||!serviceId)return;setBusy(true);setError("");setSlots([]);setSlot("");const r=await supabase.rpc("get_service_quote",{p_vehicle_id:vehicleId,p_service_id:serviceId,p_package_id:null});if(r.error||!r.data?.[0])setError(r.error?.message||"Preço ainda não cadastrado para a categoria deste veículo.");else setQuote(r.data[0] as Quote);setBusy(false)}
 async function findSlots(){if(!day||!quote)return;setBusy(true);setError("");const r=await supabase.rpc("get_available_slots",{p_date:day,p_duration_minutes:quote.duration_minutes});if(r.error)setError(r.error.message);else{const slots=(r.data||[]).filter((s:{start_time:string})=>day!==new Date().toLocaleDateString("en-CA")||s.start_time.slice(0,5)>new Date().toTimeString().slice(0,5));setSlots(slots);if(!slots.length)setNotice("Não encontramos horários livres nessa data. Selecione outro dia.")}setBusy(false)}
 async function book(){if(!customer||!vehicleId||!serviceId||!day||!slot||!quote)return;setBusy(true);setError("");const r=await supabase.rpc("create_customer_booking",{p_customer_id:customer.id,p_vehicle_id:vehicleId,p_booking_date:day,p_start_time:slot,p_service_id:serviceId,p_package_id:null,p_delivery_mode:delivery,p_observations:notes.trim()||null});if(r.error)setError(r.error.message.replaceAll("_"," "));else{setNotice("Solicitação enviada! A equipe confirmará seu horário.");setTab("resumo");setQuote(null);setSlots([]);setSlot("");await load()}setBusy(false)}
 async function saveCar(e:React.FormEvent){e.preventDefault();if(!customer)return;setBusy(true);setError("");if(!/^[A-Z]{3}[0-9][A-Z0-9][0-9]{2}$/.test(newCar.plate.trim().toUpperCase())){setError("Digite uma placa válida (formato antigo ou Mercosul).");setBusy(false);return}const r=await supabase.from("vehicles").insert({...newCar,customer_id:customer.id,year:Number(newCar.year),plate:newCar.plate.toUpperCase()});if(r.error)setError(r.error.message);else{setRegister(false);setNotice("Veículo adicionado à sua garagem.");await load()}setBusy(false)}
 const next=useMemo(()=>bookings.filter(b=>!["CANCELLED","COMPLETED","NO_SHOW"].includes(b.status)),[bookings]);
 const menu:[Tab,string,string][]=[["resumo","▦","Visão geral"],["garagem","▤","Garagem"],["agendar","▣","Agendar"],["historico","◷","Prontuário"],["catalogo","✧","Catálogo"],["perfil","♙","Perfil"]];
 if(checking)return <div className="hv hv-realWaiting">Verificando acesso seguro...</div>;
 if(!session)return <main className="hv-realAuth"><div className="hv-realAuthCard"><img src={logo} alt="Qualificar"/><span className="hv-overline">ÁREA DO CLIENTE · DADOS REAIS</span><h1>Entre na sua garagem.</h1><p>Use a mesma conta do aplicativo operacional. Esta página consulta seus dados reais, sem importar os exemplos da homologação.</p><form onSubmit={login}><label>E-mail<input type="email" required value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Senha<input type="password" required value={password} onChange={e=>setPassword(e.target.value)}/></label>{error&&<div className="hv-realError" role="alert">{error}</div>}<button disabled={busy} className="hv-button wide">{busy?"Entrando...":"Entrar com segurança"}</button></form><p>Primeiro acesso? <a href="/">Crie sua conta no cadastro operacional</a>.</p><a href="/homologacao">← Voltar à homologação demonstrativa</a></div></main>;
 return <div className="hv hv-real"><aside className="hv-side"><div className="hv-logo"><img src={logo} alt="Qualificar"/><span>GARAGEM DIGITAL</span></div><div className="hv-demoTag"><b>ÁREA CONECTADA</b><span>Dados da sua conta no Supabase</span></div><div className="hv-nav">{menu.map(([id,icon,label])=><button key={id} className={tab===id?"active":""} onClick={()=>{setTab(id);setError("");setNotice("")}}><span className="hv-navIcon">{icon}</span>{label}</button>)}</div><div className="hv-sideBottom"><span>● Conta autenticada</span><p>Os agendamentos solicitados nesta área são reais. A homologação de exemplo continua separada.</p><a href="/homologacao">Abrir demonstração ↗</a><p><button className="hv-realExit" onClick={logout}>Sair da conta</button></p></div></aside><main className="hv-main"><header className="hv-top"><span className="hv-breadcrumb">QUALIFIC.ESTETIC / CLIENTE / {menu.find(x=>x[0]===tab)?.[2]}</span><span className="hv-avatar">{(customer?.full_name||"C").slice(0,1).toUpperCase()}</span></header><div className="hv-content"><div className="hv-heading"><div><span className="hv-overline">SUA GARAGEM DIGITAL</span><h1>{menu.find(x=>x[0]===tab)?.[2]}</h1><p>Olá, {customer?.full_name?.split(" ")[0]||"cliente"}. Bem-vindo à nova experiência Qualificar.</p></div><span className="hv-pill green">Dados reais</span></div>{notice&&<div className="hv-info" role="status">{notice}</div>}{error&&<div className="hv-realError" role="alert">{error}</div>}
 {tab==="resumo"&&<><div className="hv-welcome"><div><span className="hv-overline">VISÃO GERAL</span><h2>Seu cuidado, em um só lugar.</h2><p>Acompanhe os registros vinculados à sua conta.</p></div><button className="hv-button" onClick={()=>setTab("agendar")}>Solicitar atendimento ↗</button></div><div className="hv-stats"><div><small>Seus veículos</small><strong>{cars.length}</strong><span>Garagem cadastrada</span></div><div><small>Em aberto</small><strong>{next.length}</strong><span>Solicitados ou em atendimento</span></div><div><small>Atendimentos concluídos</small><strong>{bookings.filter(b=>b.status==="COMPLETED").length}</strong><span>Histórico registrado</span></div></div><section className="hv-panel"><div className="hv-panelHead"><h3>Seus próximos cuidados</h3><small>Informações atuais do banco</small></div>{next.length?next.slice(0,8).map(b=><div className="hv-listRow" key={b.id}><span className="hv-dateBox">{b.booking_date.slice(8)}<small>{b.booking_date.slice(5,7)}</small></span><div><b>{cars.find(v=>v.id===b.vehicle_id)?.make||"Veículo"} {cars.find(v=>v.id===b.vehicle_id)?.model||""}</b><p>{niceDate(b.booking_date)} · {b.start_time.slice(0,5)}</p></div><span className="hv-pill gold">{stateName(b.status)}</span></div>):<div className="hv-empty">Nenhum atendimento em aberto.</div>}</section></>}
 {tab==="garagem"&&<><div className="hv-rightAction"><button className="hv-button" onClick={()=>setRegister(v=>!v)}>{register?"Fechar cadastro":"+ Cadastrar veículo"}</button></div>{register&&<section className="hv-panel"><div className="hv-panelHead"><h3>Novo veículo</h3><small>Cadastro real, salvo em sua conta</small></div><form onSubmit={saveCar}><div className="hv-twoFields">{([["make","Marca"],["model","Modelo"],["year","Ano"],["color","Cor"],["plate","Placa"]] as const).map(([key,label])=><label key={key}>{label}<input required value={newCar[key]} onChange={e=>setNewCar(v=>({...v,[key]:e.target.value}))}/></label>)}<label>Categoria<select value={newCar.category} onChange={e=>setNewCar(v=>({...v,category:e.target.value}))}>{[["HATCH","Hatch"],["SEDAN","Sedan"],["SUV","SUV"],["PICKUP","Caminhonete"],["OTHER","Outro"]].map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label></div><label className="hv-blockLabel">Observações permanentes<textarea value={newCar.observations} onChange={e=>setNewCar(v=>({...v,observations:e.target.value}))}/></label><button className="hv-button" disabled={busy}>Salvar veículo</button></form></section>}<div className="hv-vehicleGrid">{cars.map(v=><article className="hv-vehicle" key={v.id}><div className="hv-vehicleTop"><span className="hv-pill green">Ativo</span><span>▱</span></div><h3>{v.make} {v.model}</h3><p>{v.year} · {v.color} · {v.category}</p><span className="hv-plate">{v.plate}</span><button className="hv-outline" onClick={()=>{setVehicleId(v.id);setTab("historico")}}>Abrir prontuário ↗</button></article>)}{!cars.length&&<div className="hv-panel">Ainda não há veículos cadastrados nesta conta.</div>}</div></>}
 {tab==="catalogo"&&<><div className="hv-packageGrid">{packages.map(p=><article className="hv-pack" key={p.id}><div><span className="hv-overline">CATÁLOGO OFICIAL</span><h3>{p.name}</h3><p>{p.description||"Pacote de estética automotiva."}</p></div><div><span>Preço conforme o porte do veículo</span><button onClick={()=>setNotice("O agendamento online de pacotes ficará disponível depois da configuração de sua composição e duração. A recepção pode orientar a contratação.")}>Consultar disponibilidade ↗</button></div></article>)}</div>{!packages.length&&<div className="hv-empty">Nenhum pacote ativo no momento.</div>}</>}
 {tab==="agendar"&&<div className="hv-two booking"><section className="hv-panel"><div className="hv-panelHead"><h3>1. Selecione o veículo</h3></div><div className="hv-optionList">{cars.map(v=><button key={v.id} className={vehicleId===v.id?"selected":""} onClick={()=>setVehicleId(v.id)}><b>{v.make} {v.model}</b><small>{v.plate} · {v.category}</small></button>)}</div>{!cars.length&&<p>Cadastre seu veículo na garagem para continuar.</p>}<h3 className="hv-step">2. Escolha um serviço</h3><div className="hv-optionList">{services.map(s=><button key={s.id} className={serviceId===s.id?"selected":""} onClick={()=>setServiceId(s.id)}><b>{s.name}</b><small>{s.requires_evaluation?"Sujeito à avaliação · ":""}{s.duration_minutes} min</small></button>)}</div><div className="hv-info">Para os pacotes completos, a configuração de duração ainda está em revisão. Nesta etapa, o agendamento online é restrito a serviços configurados.</div><button className="hv-button wide" disabled={!vehicleId||!serviceId||busy} onClick={getQuote}>{busy?"Consultando...":"Consultar preço do serviço"}</button></section><div><section className="hv-panel"><div className="hv-panelHead"><h3>3. Data e horário</h3><small>Disponibilidade consultada no sistema</small></div>{quote?<><div className="hv-line"><span>Serviço</span><b>{quote.item_name}</b></div><div className="hv-line"><span>Duração</span><b>{quote.duration_minutes} min</b></div><div className="hv-line total"><span>Valor-base</span><strong>{money(quote.base_price)}</strong></div><label className="hv-blockLabel">Data<input type="date" min={new Date().toLocaleDateString("en-CA")} value={day} onChange={e=>setDay(e.target.value)}/></label><button className="hv-outline" disabled={!day||busy} onClick={findSlots}>Ver horários disponíveis</button><div className="hv-realSlots">{slots.map(s=><button key={s.start_time} className={slot===s.start_time?"active":""} onClick={()=>setSlot(s.start_time)}>{s.start_time.slice(0,5)}</button>)}</div></>:<p>Escolha o veículo e o serviço para consultar o preço e a duração.</p>}</section>{quote&&<section className="hv-panel"><div className="hv-panelHead"><h3>4. Confirmar solicitação</h3></div><label className="hv-blockLabel">Transporte<select value={delivery} onChange={e=>setDelivery(e.target.value)}><option value="CUSTOMER_BRINGS">Eu levo o veículo</option></select></label><label className="hv-blockLabel">Observações<textarea value={notes} maxLength={500} onChange={e=>setNotes(e.target.value)}/></label><div className="hv-info">Esta é uma solicitação real. O horário será registrado como solicitado e dependerá de confirmação da Qualificar.</div><button className="hv-button wide" disabled={!slot||busy} onClick={book}>{busy?"Enviando...":"Solicitar agendamento real ↗"}</button></section>}</div></div>}
 {tab==="historico"&&<><section className="hv-panel"><div className="hv-panelHead"><h3>Prontuário do veículo</h3><small>Informações exclusivas da sua conta, sem gastos acumulados</small></div><label className="hv-blockLabel">Selecione o veículo<select value={vehicleId} onChange={e=>setVehicleId(e.target.value)}>{cars.map(v=><option key={v.id} value={v.id}>{v.make} {v.model} · {v.plate}</option>)}</select></label><button className="hv-outline" onClick={()=>void refreshRecord(vehicleId)} disabled={!vehicleId||recordLoading}>{recordLoading?"Carregando...":"Atualizar prontuário"}</button></section>{record&&<><section className="hv-panel"><div className="hv-panelHead"><h3>{record.vehicle.make} {record.vehicle.model}</h3><small>{record.vehicle.plate} · {record.vehicle.year}</small></div><h4>Cuidados especiais</h4>{record.special_care.length?record.special_care.map((c,i)=><div className="hv-line" key={i}><span>{c.type}</span><b>{c.status}{c.product_used?" · "+c.product_used:""}</b></div>):<p>Sem cuidados especiais registrados. Informe a recepção sobre proteções aplicadas.</p>}</section>{record.history.map(h=><section className="hv-panel" key={h.id}><div className="hv-listRow"><div><b>{niceDate(h.booking_date)} · {h.start_time.slice(0,5)}</b><p>{h.services?.map(s=>s.name).join(" · ")||"Atendimento"}</p></div><span className="hv-pill gold">{stateName(h.status)}</span></div>{h.attendance&&<div className="hv-twoFields"><div className="hv-line"><span>KM de entrada</span><b>{h.attendance.km_entry}</b></div><div className="hv-line"><span>KM de saída</span><b>{h.attendance.km_exit??"Pendente"}</b></div></div>}{h.photos?.length>0&&<div className="hv-photos">{h.photos.map(p=><div key={p.id}>{p.url?<a href={p.url} target="_blank" rel="noreferrer"><img src={p.url} alt={p.category}/></a>:<div className="hv-empty">Imagem indisponível</div>}<span>{p.type==="BEFORE"?"Antes":"Depois"} · {p.category}</span></div>)}</div>}</section>)}{!record.history.length&&<div className="hv-empty">Nenhum atendimento registrado para este veículo.</div>}</>}{!record&&!recordLoading&&<div className="hv-empty">Selecione um veículo para consultar o prontuário.</div>}</>}
 {tab==="perfil"&&<div className="hv-two"><section className="hv-panel"><div className="hv-panelHead"><h3>Dados cadastrais</h3><small>Leitura segura do cadastro real</small></div><div className="hv-line"><span>Nome</span><b>{customer?.full_name}</b></div><div className="hv-line"><span>E-mail</span><b>{customer?.email}</b></div><div className="hv-line"><span>WhatsApp</span><b>{customer?.whatsapp}</b></div></section><section className="hv-panel"><div className="hv-panelHead"><h3>Segurança e privacidade</h3></div><p>Para alterações cadastrais sensíveis, procure a equipe Qualificar. Seu histórico e fotos são consultados somente após autenticação.</p><button className="hv-outline" onClick={logout}>Encerrar sessão</button></section></div>}
 <footer className="hv-footer"><span>QUALIFIC.ESTETIC · ÁREA CONECTADA</span><p>Os dados desta área são reais. A homologação visual fictícia permanece disponível separadamente.</p><a href="/homologacao">Ver demonstração ↗</a></footer></div></main></div>;
}
