"use client";
import {useMemo,useState} from "react";
import "./homologacao.css";

type Area="publico"|"cliente"|"operacao"|"gestao";
type DemoBooking={id:number;client:string;vehicle:string;plate:string;service:string;day:string;hour:string;status:string;price:number;km?:string};
type DemoVehicle={id:number;name:string;plate:string;year:string;category:string;color:string;care:string};
const logo="https://raw.githubusercontent.com/lucviscard-prog/qualific.estetic/main/public/logo-qualificar-correta.webp";
const price=(n:number)=>new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(n);
const packages=[{name:"Qualify Express",description:"Cuidado prático para a rotina.",prices:[80,90,100,120],duration:"1h30"},{name:"Qualify Essential",description:"Atenção ampliada ao interior e exterior.",prices:[120,140,180,180],duration:"2h30"},{name:"Qualify Detail",description:"Detalhamento para quem percebe cada acabamento.",prices:[170,190,220,250],duration:"3h30"},{name:"Qualify Prime",description:"Experiência de cuidado e apresentação elevada.",prices:[220,250,300,350],duration:"4h"},{name:"Qualify Hig Fresh",description:"Higienização com foco em renovação.",prices:[500,550,600,700],duration:"Sob avaliação"},{name:"Qualify Hig Clean",description:"Higienização interna aprofundada.",prices:[650,700,750,800],duration:"Sob avaliação"},{name:"Qualify Detail Ext Prime",description:"Tratamento detalhado da parte externa.",prices:[700,750,800,900],duration:"Sob avaliação"},{name:"Qualify Detail In Prime",description:"Cuidado minucioso do habitáculo.",prices:[850,900,950,1000],duration:"Sob avaliação"},{name:"Qualify Detail Ultimate",description:"Experiência completa de estética automotiva.",prices:[1400,1500,1600,1700],duration:"Sob avaliação"}];
const labels:Record<string,string>={REQUESTED:"Solicitado",CONFIRMED:"Confirmado",CUSTOMER_ARRIVED:"Check-in",IN_SERVICE:"Em serviço",AWAITING_PICKUP:"Pronto",COMPLETED:"Entregue",CANCELLED:"Cancelado"};
const initialBookings:DemoBooking[]=[{id:101,client:"Lucas (exemplo)",vehicle:"Volkswagen Gol",plate:"ABC1D23",service:"Qualify Detail",day:"2026-10-02",hour:"09:00",status:"CONFIRMED",price:170},{id:102,client:"Marina Oliveira",vehicle:"Honda HR-V",plate:"DEF4G56",service:"Qualify Prime",day:"2026-10-02",hour:"13:00",status:"REQUESTED",price:300},{id:103,client:"Rafael Martins",vehicle:"Toyota Corolla",plate:"GHI7J89",service:"Qualify Essential",day:"2026-10-03",hour:"09:00",status:"COMPLETED",price:140}];
const initialVehicles:DemoVehicle[]=[{id:1,name:"Volkswagen Gol",plate:"ABC1D23",year:"2002",category:"Hatch",color:"Prata",care:"Não sei informar"},{id:2,name:"Nissan Kicks",plate:"JKL2M34",year:"2019",category:"SUV",color:"Branco",care:"Vitrificação: sim"}];
const initialTasks=["Frente","Traseira","Lateral esquerda","Lateral direita","Interior dianteiro","Interior traseiro","Painel","Rodas","Porta-malas","Pertences","Danos preexistentes"];
const areas:{id:Area;name:string;subtitle:string}[]=[{id:"publico",name:"Site público",subtitle:"Primeiro contato"},{id:"cliente",name:"Área do cliente",subtitle:"Minha garagem"},{id:"operacao",name:"Operação",subtitle:"Equipe e atendimentos"},{id:"gestao",name:"Gestão",subtitle:"Administração"}];
const subtitles:Record<string,string>={inicio:"Seu carro merece cuidado sob medida.",pacotes:"Cada detalhe tem seu momento.",sobre:"Estética automotiva de verdade.",contato:"Estamos perto de você.",resumo:"Seu cuidado em um só lugar.",garagem:"Cada veículo, uma história.",agendar:"Reserve seu próximo cuidado.",historico:"Tudo registrado com clareza.",perfil:"Seus dados e preferências.",agenda:"Cada atendimento no seu ritmo.",vistoria:"O veículo documentado da chegada à saída.",logistica:"Retirada e entrega organizadas.",clientes:"Relacionamento construído no detalhe.",catalogo:"Serviços e pacotes organizados.",financeiro:"Uma visão prática dos números.",crm:"Clientes, retornos e oportunidades.",mensagens:"Comunicação alinhada ao atendimento.",configuracoes:"Controle da operação."};
const menus:Record<Area,{id:string;name:string;icon:string}[]>={
 publico:[{id:"inicio",name:"Início",icon:"⌂"},{id:"pacotes",name:"Pacotes",icon:"✧"},{id:"sobre",name:"Sobre nós",icon:"◎"},{id:"contato",name:"Contato",icon:"↗"}],
 cliente:[{id:"resumo",name:"Visão geral",icon:"▦"},{id:"garagem",name:"Minha garagem",icon:"▤"},{id:"agendar",name:"Agendar",icon:"▣"},{id:"historico",name:"Histórico",icon:"◷"},{id:"perfil",name:"Meu perfil",icon:"♙"}],
 operacao:[{id:"agenda",name:"Agenda",icon:"▦"},{id:"vistoria",name:"Check-in e vistoria",icon:"✓"},{id:"logistica",name:"Logística",icon:"⇄"}],
 gestao:[{id:"clientes",name:"Clientes",icon:"♙"},{id:"catalogo",name:"Catálogo",icon:"▤"},{id:"financeiro",name:"Financeiro",icon:"▥"},{id:"crm",name:"CRM",icon:"◎"},{id:"mensagens",name:"Comunicação",icon:"✉"},{id:"configuracoes",name:"Configurações",icon:"⚙"}]
};
function Pill({children,kind="neutral"}:{children:React.ReactNode;kind?:string}){return <span className={"hv-pill "+kind}>{children}</span>}
function Panel({title,sub,children,className=""}:{title:string;sub?:string;children:React.ReactNode;className?:string}){return <section className={"hv-panel "+className}><div className="hv-panelHead"><h3>{title}</h3>{sub&&<small>{sub}</small>}</div>{children}</section>}
export default function Homologacao(){
 const [area,setArea]=useState<Area>("publico"),[tab,setTab]=useState("inicio");
 const [bookings,setBookings]=useState(initialBookings),[vehicles,setVehicles]=useState(initialVehicles);
 const [selectedVehicle,setSelectedVehicle]=useState(1),[selectedPack,setSelectedPack]=useState(0),[selectedDay,setSelectedDay]=useState("2026-10-05"),[selectedTime,setSelectedTime]=useState("09:00"),[category,setCategory]=useState(0);
 const [notice,setNotice]=useState(""),[filter,setFilter]=useState(""),[selectedBooking,setSelectedBooking]=useState(101);
 const [checked,setChecked]=useState<string[]>([]),[damage,setDamage]=useState(""),[belongings,setBelongings]=useState(""),[km,setKm]=useState("82450"),[dirt,setDirt]=useState("Média");
 const [images,setImages]=useState<{name:string;url:string;stage:string}[]>([]),[stage,setStage]=useState("Antes");
 const [addVehicle,setAddVehicle]=useState(false),[newName,setNewName]=useState(""),[newPlate,setNewPlate]=useState("");
 const [marketing,setMarketing]=useState(false),[delivery,setDelivery]=useState("Cliente leva o veículo");
 const [crmFilter,setCrmFilter]=useState("Todos"),[catalogSearch,setCatalogSearch]=useState("");
 const [settings,setSettings]=useState({open:"08:00",close:"18:00",box:"Box 01",reminder:true});
 const [messageText,setMessageText]=useState("Olá! Seu veículo está pronto para retirada. Agradecemos pela confiança na Qualificar.");
 const chosen=vehicles.find(v=>v.id===selectedVehicle)||vehicles[0];
 const inspected=bookings.find(b=>b.id===selectedBooking)||bookings[0];
 const summary=useMemo(()=>({total:bookings.length,pending:bookings.filter(b=>b.status==="REQUESTED").length,active:bookings.filter(b=>["CONFIRMED","CUSTOMER_ARRIVED","IN_SERVICE"].includes(b.status)).length,done:bookings.filter(b=>b.status==="COMPLETED").length}),[bookings]);
 function navigate(a:Area,t:string){setArea(a);setTab(t);setNotice("");window.scrollTo({top:0,behavior:"smooth"})}
 function toast(s:string){setNotice(s);window.setTimeout(()=>setNotice(""),5000)}
 function changeStatus(id:number,status:string){setBookings(old=>old.map(b=>b.id===id?{...b,status}:b));toast("Status atualizado nesta demonstração. Nenhum dado real foi alterado.")}
 function addBooking(){const p=packages[selectedPack];const v=chosen;setBookings(old=>[{id:Math.max(...old.map(x=>x.id),100)+1,client:"Lucas (exemplo)",vehicle:v.name,plate:v.plate,service:p.name,day:selectedDay,hour:selectedTime,status:"REQUESTED",price:p.prices[category]},...old]);navigate("cliente","historico");toast("Agendamento demonstrativo criado com sucesso.")}
 function saveVehicle(){if(!newName.trim()||!newPlate.trim())return toast("Informe o nome e a placa do veículo.");const id=Math.max(...vehicles.map(v=>v.id))+1;setVehicles(old=>[...old,{id,name:newName,plate:newPlate.toUpperCase(),year:"2024",category:"A definir",color:"A definir",care:"Não sei informar"}]);setSelectedVehicle(id);setNewName("");setNewPlate("");setAddVehicle(false);toast("Veículo adicionado à garagem demonstrativa.")}
 function photoChange(files:FileList|null){if(!files)return;const next=Array.from(files).filter(f=>f.type.startsWith("image/")).map(f=>({name:f.name,url:URL.createObjectURL(f),stage}));setImages(old=>[...old,...next]);toast("Prévia local adicionada. Nesta homologação as fotos não são enviadas ao banco.")}
 const nav=(a:Area,t:string,label:string,alt=false)=><button type="button" className={alt?"hv-outline":"hv-button"} onClick={()=>navigate(a,t)}>{label} <span aria-hidden>↗</span></button>;
 return <div className="hv">
  <aside className="hv-side">
   <div className="hv-logo"><img src={logo} alt="Qualificar Estética Automotiva"/><span>ESTETIC · STUDIO</span></div>
   <div className="hv-demoTag"><b>HOMOLOGAÇÃO GERAL</b><span>Ambiente demonstrativo v1</span></div><a className="hv-liveLink" href="/homologacao/cliente-real">Testar área conectada ↗</a><a className="hv-liveLink" href="/homologacao/pacotes">Configurar pacotes (gestão) ↗</a>
   <div className="hv-areaNav">{areas.map(a=><button key={a.id} className={area===a.id?"active":""} onClick={()=>navigate(a.id,menus[a.id][0].id)}><strong>{a.name}</strong><small>{a.subtitle}</small></button>)}</div>
   <div className="hv-sideDivider"/>
   <div className="hv-nav">{menus[area].map(m=><button key={m.id} className={tab===m.id?"active":""} onClick={()=>navigate(area,m.id)}><span className="hv-navIcon">{m.icon}</span>{m.name}</button>)}</div>
   <div className="hv-sideBottom"><span>● Visão de validação</span><p>Os controles simulam a experiência. A operação real permanece separada.</p><a href="/" target="_blank" rel="noreferrer">Abrir aplicativo operacional ↗</a></div>
  </aside>
  <main className="hv-main">
   <header className="hv-top"><div className="hv-breadcrumb">QUALIFIC.ESTETIC <span>/</span> {areas.find(a=>a.id===area)?.name} <span>/</span> {menus[area].find(m=>m.id===tab)?.name}</div><div className="hv-topRight"><Pill kind="gold">Modo demonstração</Pill><span className="hv-avatar">Q</span></div></header>
   {notice&&<div className="hv-toast" role="status">{notice}<button onClick={()=>setNotice("")}>×</button></div>}
   <div className="hv-content">
    <div className="hv-heading"><div><span className="hv-overline">EXPERIÊNCIA QUALIFICAR / {area.toUpperCase()}</span><h1>{menus[area].find(m=>m.id===tab)?.name}</h1><p>{subtitles[tab]}</p></div><div className="hv-headingActions">{area==="publico"?nav("cliente","resumo","Explorar área do cliente"):nav("publico","inicio","Ver site público",true)}</div></div>
    {area==="publico"&&tab==="inicio"&&<><div className="hv-hero"><div><span className="hv-overline light">ESTÉTICA AUTOMOTIVA · MARECHAL CÂNDIDO RONDON</span><h2>Mais que brilho.<br/>Uma experiência de cuidado.</h2><p>Seu veículo tem sua própria história. Nós valorizamos cada detalhe dela, da primeira avaliação à entrega.</p><div className="hv-actions">{nav("cliente","agendar","Agendar um cuidado")}{nav("publico","pacotes","Conhecer os pacotes",true)}</div></div><div className="hv-heroArt"><div className="hv-orbit">Q</div><span>DETAILING EXPERIENCE</span></div></div><div className="hv-three"><Panel title="Atendimento pensado para você" sub="01 · Personalização"><p>Pacotes e serviços organizados por necessidade, categoria e avaliação técnica.</p></Panel><Panel title="Transparência em cada etapa" sub="02 · Confiança"><p>Registros, inspeção inicial e fotos de antes e depois vinculadas ao atendimento.</p></Panel><Panel title="Seu histórico, sempre perto" sub="03 · Garagem digital"><p>Uma ficha por veículo com serviços realizados e cuidados especiais.</p></Panel></div><div className="hv-splitBanner"><div><span className="hv-overline">CURADORIA DE SERVIÇOS</span><h2>Há um cuidado certo para cada momento.</h2><p>Do cuidado cotidiano ao detalhamento mais completo.</p></div>{nav("publico","pacotes","Ver os 9 pacotes")}</div></>}
    {area==="publico"&&tab==="pacotes"&&<><div className="hv-toolbar"><div className="hv-segments">{["Hatch","Sedan","SUV","Caminhonete"].map((x,i)=><button className={i===category?"active":""} key={x} onClick={()=>setCategory(i)}>{x}</button>)}</div><small>Valores referenciais para validação da apresentação</small></div><div className="hv-packageGrid">{packages.map((p,i)=><article className="hv-pack" key={p.name}><div><span className="hv-overline">PACOTE {String(i+1).padStart(2,"0")}</span><h3>{p.name}</h3><p>{p.description}</p></div><div><small>A partir de</small><strong>{price(p.prices[category])}</strong><span>{p.duration}</span><button onClick={()=>{setSelectedPack(i);navigate("cliente","agendar")}}>Selecionar pacote ↗</button></div></article>)}</div></>}
    {area==="publico"&&tab==="sobre"&&<><div className="hv-hero compact"><div><span className="hv-overline light">A NOSSA ESSÊNCIA</span><h2>Não é apenas uma lavagem.</h2><p>O conceito Qualificar reúne estética, método e atenção aos materiais. O atendimento foi pensado para comunicar os detalhes, respeitar particularidades de cada carro e registrar o cuidado ao longo do tempo.</p></div><div className="hv-heroArt"><div className="hv-orbit">Q</div></div></div><div className="hv-three">{["Avaliação individual","Técnicas e produtos adequados","Histórico digital de cada carro"].map((x,i)=><Panel key={x} title={x} sub={"PILAR 0"+(i+1)}><p>Uma experiência organizada do primeiro contato ao acompanhamento após a entrega.</p></Panel>)}</div></>}
    {area==="publico"&&tab==="contato"&&<div className="hv-two"><Panel title="Vamos conversar?" sub="Contato comercial"><p>Atendimento em Marechal Cândido Rondon, Paraná. Informações comerciais e confirmação de disponibilidade devem ser verificadas nos canais oficiais.</p><div className="hv-contact"><span>WhatsApp</span><strong>Atendimento digital Qualificar</strong></div><button className="hv-button" onClick={()=>toast("A integração de WhatsApp será conectada após homologação.")}>Iniciar conversa ↗</button></Panel><Panel title="Uma experiência conectada" sub="Agende e acompanhe"><p>Escolha seu veículo, selecione um cuidado, confira o preço-base e acompanhe o status na garagem digital.</p>{nav("cliente","agendar","Simular agendamento")}</Panel></div>}
    {area==="cliente"&&tab==="resumo"&&<><div className="hv-welcome"><div><span className="hv-overline">OLÁ, LUCAS (PERFIL EXEMPLO)</span><h2>Que bom ter você de volta.</h2><p>Sua garagem está pronta para o próximo cuidado.</p></div>{nav("cliente","agendar","Novo agendamento")}</div><div className="hv-stats"><div><small>Meus veículos</small><strong>{vehicles.length}</strong><span>Garagem cadastrada</span></div><div><small>Agendamentos ativos</small><strong>{bookings.filter(b=>b.client.includes("Lucas")&&!["COMPLETED","CANCELLED"].includes(b.status)).length}</strong><span>Acompanhe cada etapa</span></div><div><small>Serviços realizados</small><strong>{bookings.filter(b=>b.client.includes("Lucas")&&b.status==="COMPLETED").length}</strong><span>Seu histórico</span></div></div><div className="hv-two"><Panel title="Próximos cuidados" sub="Acompanhamento em tempo real"><div className="hv-list">{bookings.filter(b=>b.client.includes("Lucas")).slice(0,3).map(b=><div className="hv-listRow" key={b.id}><span className="hv-dateBox">{b.day.slice(8)}<small>{b.day.slice(5,7)}</small></span><div><b>{b.service}</b><p>{b.vehicle} · {b.hour}</p></div><Pill kind={b.status==="COMPLETED"?"green":"gold"}>{labels[b.status]}</Pill></div>)}</div><button className="hv-inline" onClick={()=>navigate("cliente","historico")}>Abrir histórico completo →</button></Panel><Panel title="Sua garagem" sub="Prontuários individuais">{vehicles.slice(0,2).map(v=><div className="hv-vehicleMini" key={v.id}><span>▱</span><div><b>{v.name}</b><small>{v.plate} · {v.year}</small></div></div>)}{nav("cliente","garagem","Gerenciar veículos",true)}</Panel></div></>}
    {area==="cliente"&&tab==="garagem"&&<><div className="hv-rightAction"><button className="hv-button" onClick={()=>setAddVehicle(x=>!x)}>{addVehicle?"Fechar cadastro":"+ Adicionar veículo"}</button></div>{addVehicle&&<Panel title="Novo veículo demonstrativo" sub="O cadastro operacional tem campos completos de marca, modelo, ano e cuidados especiais"><div className="hv-twoFields"><label>Marca e modelo<input value={newName} onChange={e=>setNewName(e.target.value)} placeholder="Ex.: Fiat Argo"/></label><label>Placa<input value={newPlate} onChange={e=>setNewPlate(e.target.value)} maxLength={7} placeholder="ABC1D23"/></label></div><button className="hv-button" onClick={saveVehicle}>Adicionar à demonstração</button></Panel>}<div className="hv-vehicleGrid">{vehicles.map(v=><article className="hv-vehicle" key={v.id}><div className="hv-vehicleTop"><Pill kind="green">Ficha ativa</Pill><span>▱</span></div><h3>{v.name}</h3><p>{v.year} · {v.color} · {v.category}</p><div className="hv-plate">{v.plate}</div><div className="hv-carLine"><small>Cuidados especiais</small><b>{v.care}</b></div><div className="hv-carLine"><small>Prontuário digital</small><b>{bookings.filter(b=>b.plate===v.plate).length} registro(s)</b></div><button className="hv-outline" onClick={()=>{setSelectedVehicle(v.id);navigate("cliente","historico")}}>Ver prontuário ↗</button></article>)}</div></>}
    {area==="cliente"&&tab==="agendar"&&<div className="hv-two booking"><Panel title="1. Escolha seu veículo" sub="Garagem digital"><div className="hv-optionList">{vehicles.map(v=><button className={selectedVehicle===v.id?"selected":""} key={v.id} onClick={()=>setSelectedVehicle(v.id)}><b>{v.name}</b><small>{v.plate} · {v.category}</small></button>)}</div><h3 className="hv-step">2. Porte do veículo para simulação</h3><div className="hv-segments">{["Hatch","Sedan","SUV","Caminhonete"].map((x,i)=><button key={x} className={category===i?"active":""} onClick={()=>setCategory(i)}>{x}</button>)}</div><h3 className="hv-step">3. Escolha o pacote</h3><div className="hv-optionList">{packages.map((p,i)=><button key={p.name} className={selectedPack===i?"selected":""} onClick={()=>setSelectedPack(i)}><b>{p.name}</b><small>{price(p.prices[category])} · {p.duration}</small></button>)}</div></Panel><div><Panel title="4. Data, horário e logística" sub="Disponibilidade ilustrativa"><div className="hv-twoFields"><label>Data<input type="date" value={selectedDay} onChange={e=>setSelectedDay(e.target.value)}/></label><label>Horário<select value={selectedTime} onChange={e=>setSelectedTime(e.target.value)}>{["08:00","09:00","10:00","13:00","14:00","15:00","16:00"].map(x=><option key={x}>{x}</option>)}</select></label></div><label className="hv-blockLabel">Como o veículo chegará?<select value={delivery} onChange={e=>setDelivery(e.target.value)}><option>Cliente leva o veículo</option><option>Solicitar retirada pela Qualificar</option></select></label>{delivery.includes("retirada")&&<div className="hv-info">A confirmação da coleta e possíveis custos dependem da disponibilidade logística.</div>}</Panel><Panel title="Resumo da solicitação" sub="Confirme seus dados"><div className="hv-line"><span>Veículo</span><b>{chosen.name}</b></div><div className="hv-line"><span>Pacote</span><b>{packages[selectedPack].name}</b></div><div className="hv-line"><span>Data e hora</span><b>{selectedDay.split("-").reverse().join("/")} · {selectedTime}</b></div><div className="hv-line total"><span>Valor-base estimado</span><strong>{price(packages[selectedPack].prices[category])}</strong></div><p className="hv-fine">Simulação de fluxo, sem reservar horário real ou gerar cobrança.</p><button className="hv-button wide" onClick={addBooking}>Criar solicitação demonstrativa ↗</button></Panel></div></div>}
    {area==="cliente"&&tab==="historico"&&<><div className="hv-toolbar"><div className="hv-segments"><button className={filter===""?"active":""} onClick={()=>setFilter("")}>Todos</button><button className={filter==="COMPLETED"?"active":""} onClick={()=>setFilter("COMPLETED")}>Concluídos</button><button className={filter==="REQUESTED"?"active":""} onClick={()=>setFilter("REQUESTED")}>Solicitados</button></div><select value={selectedVehicle} onChange={e=>setSelectedVehicle(Number(e.target.value))}>{vehicles.map(v=><option key={v.id} value={v.id}>{v.name}</option>)}</select></div><Panel title={"Prontuário · "+chosen.name} sub={"Placa "+chosen.plate+" · Somente serviços, datas e registros visíveis ao cliente"}><div className="hv-timeline">{bookings.filter(b=>b.plate===chosen.plate&&(!filter||b.status===filter)).length?bookings.filter(b=>b.plate===chosen.plate&&(!filter||b.status===filter)).map(b=><div className="hv-event" key={b.id}><span className="hv-eventDot"/><div><small>{b.day.split("-").reverse().join("/")} · {b.hour}</small><h3>{b.service}</h3><p>Atendimento #{b.id} · {b.vehicle}</p><Pill kind={b.status==="COMPLETED"?"green":"gold"}>{labels[b.status]}</Pill></div></div>):<p className="hv-muted">Ainda não há registros com esse filtro.</p>}</div><div className="hv-info">Na versão operacional, o cliente terá acesso às fotos autorizadas e às informações pertinentes ao próprio veículo. Valores acumulados de gastos são reservados à gestão.</div></Panel></>}
    {area==="cliente"&&tab==="perfil"&&<div className="hv-two"><Panel title="Meus dados" sub="Perfil fictício de demonstração"><div className="hv-formStack"><label>Nome completo<input defaultValue="Lucas (exemplo)"/></label><label>E-mail<input defaultValue="cliente.exemplo@qualificar.test"/></label><label>WhatsApp<input defaultValue="(45) 99999-0000"/></label><label>CEP<input defaultValue="85960-000"/></label></div><button className="hv-button" onClick={()=>toast("As alterações de perfil são apenas ilustrativas nesta versão.")}>Simular atualização</button></Panel><Panel title="Preferências de comunicação" sub="Consentimentos separados"><label className="hv-check"><input type="checkbox" checked readOnly/> Avisos transacionais de atendimento</label><label className="hv-check"><input type="checkbox" checked={marketing} onChange={e=>setMarketing(e.target.checked)}/> Comunicações e novidades comerciais</label><p className="hv-fine">A finalidade de cada consentimento é apresentada separadamente. Nada é gravado nesta prévia.</p></Panel></div>}
    {area==="operacao"&&tab==="agenda"&&<><div className="hv-stats"><div><small>Atendimentos na prévia</small><strong>{summary.total}</strong><span>Agendados e concluídos</span></div><div><small>Aguardando confirmação</small><strong>{summary.pending}</strong><span>Solicitações novas</span></div><div><small>Em andamento / confirmados</small><strong>{summary.active}</strong><span>Fluxo operacional</span></div><div><small>Finalizados</small><strong>{summary.done}</strong><span>Histórico concluído</span></div></div><Panel title="Linha de atendimento" sub="Selecione as ações para percorrer os estados"><div className="hv-opsList">{[...bookings].sort((a,b)=>a.day.localeCompare(b.day)||a.hour.localeCompare(b.hour)).map(b=><div className="hv-opsRow" key={b.id}><div className="hv-opsTime">{b.hour}<small>{b.day.slice(8)}/{b.day.slice(5,7)}</small></div><div className="hv-opsDesc"><Pill kind={b.status==="COMPLETED"?"green":"gold"}>{labels[b.status]||b.status}</Pill><h3>{b.vehicle} · {b.plate}</h3><p>{b.client} · {b.service} · {price(b.price)}</p></div><div className="hv-opsActions">{b.status==="REQUESTED"&&<button onClick={()=>changeStatus(b.id,"CONFIRMED")}>Confirmar</button>}{b.status==="CONFIRMED"&&<button onClick={()=>changeStatus(b.id,"CUSTOMER_ARRIVED")}>Check-in</button>}{b.status==="CUSTOMER_ARRIVED"&&<button onClick={()=>{setSelectedBooking(b.id);navigate("operacao","vistoria")}}>Vistoria</button>}{b.status==="IN_SERVICE"&&<button onClick={()=>changeStatus(b.id,"AWAITING_PICKUP")}>Marcar pronto</button>}{b.status==="AWAITING_PICKUP"&&<button onClick={()=>changeStatus(b.id,"COMPLETED")}>Registrar entrega</button>}{b.status==="COMPLETED"&&<span className="hv-muted">Concluído ✓</span>}{b.status==="CUSTOMER_ARRIVED"&&<button className="accent" onClick={()=>changeStatus(b.id,"IN_SERVICE")}>Iniciar</button>}</div></div>)}</div></Panel></>}
    {area==="operacao"&&tab==="vistoria"&&<><div className="hv-two"><Panel title="Atendimento em inspeção" sub="Selecione o atendimento de exemplo"><label className="hv-blockLabel">Atendimento<select value={selectedBooking} onChange={e=>setSelectedBooking(Number(e.target.value))}>{bookings.map(b=><option key={b.id} value={b.id}>#{b.id} · {b.vehicle} · {b.plate}</option>)}</select></label><div className="hv-line"><span>Cliente</span><b>{inspected.client}</b></div><div className="hv-line"><span>Serviço</span><b>{inspected.service}</b></div><div className="hv-line"><span>Status</span><Pill kind="gold">{labels[inspected.status]}</Pill></div><div className="hv-twoFields"><label>KM na entrada<input inputMode="numeric" value={km} onChange={e=>setKm(e.target.value)}/></label><label>Nível de sujeira<select value={dirt} onChange={e=>setDirt(e.target.value)}>{["Leve","Média","Pesada","Extrema"].map(x=><option key={x}>{x}</option>)}</select></label></div><label className="hv-blockLabel">Pertences e porta-malas<textarea value={belongings} onChange={e=>setBelongings(e.target.value)} placeholder="Ex.: itens deixados pelo proprietário"/></label><label className="hv-blockLabel">Danos preexistentes<textarea value={damage} onChange={e=>setDamage(e.target.value)} placeholder="Descreva riscos, manchas e amassados"/></label></Panel><Panel title="Checklist visual" sub={checked.length+" de "+initialTasks.length+" itens marcados"}><div className="hv-checkGrid">{initialTasks.map(x=><label key={x} className={checked.includes(x)?"active":""}><input type="checkbox" checked={checked.includes(x)} onChange={e=>setChecked(old=>e.target.checked?[...old,x]:old.filter(y=>y!==x))}/>{x}</label>)}</div><div className="hv-info">⚠ Cuidado especial no exemplo: status ainda não confirmado. Validar materiais e tratamentos antes de aplicar produtos.</div><button className="hv-button wide" onClick={()=>toast("Checklist preenchido na demonstração. A vistoria real segue no aplicativo operacional.")}>Validar preenchimento do checklist</button></Panel></div><Panel title="Registros fotográficos" sub="Galeria demonstrativa: as imagens ficam somente nesta sessão"><div className="hv-photoInput"><select value={stage} onChange={e=>setStage(e.target.value)}><option>Antes</option><option>Depois</option></select><label>Selecionar imagens<input type="file" accept="image/*" multiple onChange={e=>photoChange(e.target.files)}/></label></div>{images.length>0?<div className="hv-photos">{images.map((x,i)=><div key={i}><img src={x.url} alt={x.name}/><span>{x.stage} · {x.name}</span></div>)}</div>:<div className="hv-empty">Adicione imagens para visualizar a distribuição da galeria Antes e Depois.</div>}</Panel></>}
    {area==="operacao"&&tab==="logistica"&&<div className="hv-two"><Panel title="Coleta de veículos" sub="Fluxo previsto de retirada"><div className="hv-process">{["Solicitação do cliente","Análise de rota e disponibilidade","Confirmação pela recepção","Coleta e registro de KM","Check-in na unidade"].map((x,i)=><div key={x}><span>{i+1}</span><b>{x}</b></div>)}</div><button className="hv-button" onClick={()=>toast("Fluxo logístico aprovado visualmente nesta prévia; integração real pendente.")}>Simular nova coleta</button></Panel><Panel title="Devolução e entrega" sub="Etapas ligadas ao atendimento"><div className="hv-process">{["Conclusão do serviço","Inspeção final e fotos","Confirmação do pagamento","KM de saída e pertences","Entrega ou retorno ao endereço"].map((x,i)=><div key={x}><span>{i+1}</span><b>{x}</b></div>)}</div><div className="hv-info">A agenda reserva um box operacional. Encaixes adicionais precisam de autorização da equipe.</div></Panel></div>}
    {area==="gestao"&&tab==="clientes"&&<><div className="hv-toolbar"><input className="hv-search" placeholder="Buscar cliente, placa ou veículo" value={filter} onChange={e=>setFilter(e.target.value)}/><Pill kind="green">Exemplos fictícios</Pill></div><Panel title="Relacionamento e prontuários" sub="A gestão visualiza histórico, recorrência e valores internos"><div className="hv-dataTable"><div className="hv-tableHead"><span>Cliente</span><span>Veículo</span><span>Atendimentos</span><span>Total de referência</span><span>Perfil</span></div>{[...new Map(bookings.map(b=>[b.client,b.client])).values()].filter(n=>n.toLowerCase().includes(filter.toLowerCase())||bookings.some(b=>b.client===n&&(b.plate.toLowerCase().includes(filter.toLowerCase())||b.vehicle.toLowerCase().includes(filter.toLowerCase())))).map(n=>{const rows=bookings.filter(b=>b.client===n);return <div className="hv-tableRow" key={n}><b>{n}</b><span>{rows[0].vehicle}</span><span>{rows.length}</span><b>{price(rows.reduce((s,b)=>s+(b.status==="COMPLETED"?b.price:0),0))}</b><Pill kind="green">{rows.length>1?"Recorrente":"Cadastrado"}</Pill></div>})}</div></Panel></>}
    {area==="gestao"&&tab==="catalogo"&&<><div className="hv-toolbar"><input className="hv-search" value={catalogSearch} onChange={e=>setCatalogSearch(e.target.value)} placeholder="Buscar pacotes"/><Pill kind="gold">Tabela de referência</Pill></div><Panel title="Pacotes e faixas de preço" sub="Exibição dos 9 pacotes para aprovação da apresentação"><div className="hv-dataTable"><div className="hv-tableHead five"><span>Pacote</span><span>Hatch</span><span>Sedan</span><span>SUV</span><span>Caminhonete</span></div>{packages.filter(p=>p.name.toLowerCase().includes(catalogSearch.toLowerCase())).map(p=><div className="hv-tableRow five" key={p.name}><b>{p.name}</b>{p.prices.map((v,i)=><span key={i}>{price(v)}</span>)}</div>)}</div></Panel><div className="hv-info">O cadastro completo de serviços, composição de pacotes, disponibilidade online e adicionais exige revisão funcional antes do lançamento.</div></>}
    {area==="gestao"&&tab==="financeiro"&&<><div className="hv-stats"><div><small>Receita concluída ilustrativa</small><strong>{price(bookings.filter(b=>b.status==="COMPLETED").reduce((s,b)=>s+b.price,0))}</strong><span>Somente atendimentos finalizados</span></div><div><small>Valores em aberto</small><strong>{price(bookings.filter(b=>!["COMPLETED","CANCELLED"].includes(b.status)).reduce((s,b)=>s+b.price,0))}</strong><span>Agendamentos em curso</span></div><div><small>Ticket médio ilustrativo</small><strong>{price(bookings.reduce((s,b)=>s+b.price,0)/Math.max(1,bookings.length))}</strong><span>Base dos dados demonstrativos</span></div></div><div className="hv-two"><Panel title="Composição do atendimento" sub="Visão interna de valores"><div className="hv-line"><span>Preço-base</span><b>{price(220)}</b></div><div className="hv-line"><span>Adicional aprovado (exemplo)</span><b>{price(40)}</b></div><div className="hv-line"><span>Desconto (exemplo)</span><b>- {price(10)}</b></div><div className="hv-line total"><span>Total demonstrativo</span><strong>{price(250)}</strong></div><button className="hv-button" onClick={()=>toast("Nenhuma cobrança real é realizada na homologação.")}>Simular fechamento</button></Panel><Panel title="Painel administrativo" sub="Indicadores previstos"><div className="hv-chart">{[38,62,48,77,51,89,70].map((n,i)=><div key={i}><span style={{height:n+"%"}}/><small>{["Seg","Ter","Qua","Qui","Sex","Sáb","Dom"][i]}</small></div>)}</div><p className="hv-fine">Gráfico visual fictício. Integração com lançamentos e meios de pagamento permanece pendente.</p></Panel></div></>}
    {area==="gestao"&&tab==="crm"&&<><div className="hv-toolbar"><div className="hv-segments">{["Todos","Recorrentes","Sem retorno","Aniversariantes"].map(x=><button key={x} className={crmFilter===x?"active":""} onClick={()=>setCrmFilter(x)}>{x}</button>)}</div></div><div className="hv-three">{[{title:"Clientes ativos",n:"42",desc:"Indicador fictício"},{title:"Retorno a acompanhar",n:"08",desc:"Indicador fictício"},{title:"Oportunidades de contato",n:"13",desc:"Indicador fictício"}].map(x=><Panel key={x.title} title={x.title} sub={x.desc}><strong className="hv-largeNumber">{x.n}</strong></Panel>)}</div><Panel title={"Segmento · "+crmFilter} sub="Exemplos da comunicação planejada"><div className="hv-listRow"><span className="hv-roundIcon">◎</span><div><b>{crmFilter==="Todos"?"Programa de relacionamento":crmFilter}</b><p>Avisos de manutenção estética, retorno programado e acompanhamento pós-serviço.</p></div><button className="hv-outline" onClick={()=>toast("Campanha simulada; nenhuma mensagem foi enviada.")}>Pré-visualizar ação</button></div></Panel></>}
    {area==="gestao"&&tab==="mensagens"&&<div className="hv-two"><Panel title="Recepção virtual" sub="Modelos transacionais"><div className="hv-optionList">{["Confirmação de agendamento","Lembrete no dia anterior","Veículo em atendimento","Pronto para retirada","Pós-atendimento"].map((x,i)=><button key={x} onClick={()=>setMessageText(["Olá! Sua solicitação de agendamento foi recebida. Nossa equipe confirmará a disponibilidade.","Olá! Passando para lembrar seu atendimento de amanhã na Qualificar.","Seu veículo já está em atendimento. Estamos cuidando dos detalhes.","Olá! Seu veículo está pronto para retirada. Agradecemos pela confiança na Qualificar.","Agradecemos sua visita! Como foi sua experiência com a Qualificar?"][i])}>{x}<small>Visualizar modelo →</small></button>)}</div></Panel><Panel title="Prévia de mensagem" sub="Nenhum WhatsApp conectado nesta demonstração"><div className="hv-chat"><div className="hv-chatBubble">{messageText}</div></div><label className="hv-blockLabel">Editar texto de teste<textarea value={messageText} onChange={e=>setMessageText(e.target.value)}/></label><button className="hv-button" onClick={()=>toast("Prévia aprovada localmente. O envio real depende de integração e consentimentos.")}>Validar modelo</button></Panel></div>}
    {area==="gestao"&&tab==="configuracoes"&&<div className="hv-two"><Panel title="Funcionamento e capacidade" sub="Configuração demonstrativa"><div className="hv-twoFields"><label>Abertura<input type="time" value={settings.open} onChange={e=>setSettings(s=>({...s,open:e.target.value}))}/></label><label>Encerramento<input type="time" value={settings.close} onChange={e=>setSettings(s=>({...s,close:e.target.value}))}/></label></div><label className="hv-blockLabel">Box de agendamento<input value={settings.box} onChange={e=>setSettings(s=>({...s,box:e.target.value}))}/></label><label className="hv-check"><input type="checkbox" checked={settings.reminder} onChange={e=>setSettings(s=>({...s,reminder:e.target.checked}))}/> Lembretes transacionais habilitados</label><button className="hv-button" onClick={()=>toast("Configurações demonstrativas salvas somente na tela.")}>Validar configurações</button></Panel><Panel title="Papéis e permissões" sub="Desenho previsto para produção">{["Administrador","Gestor","Recepção","Profissional","Cliente"].map((x,i)=><div className="hv-line" key={x}><span>{x}</span><Pill kind={i===4?"green":"gold"}>{["Acesso total","Gestão e relatórios","Agenda e clientes","Execução e vistoria","Dados próprios"][i]}</Pill></div>)}<div className="hv-info">As permissões reais seguem as regras de acesso do banco; esta tela apenas demonstra a organização desejada.</div></Panel></div>}
    <footer className="hv-footer"><span>QUALIFIC.ESTETIC · HOMOLOGAÇÃO</span><p>Dados fictícios e simulações locais. Não utilizar esta prévia como comprovante de agendamento, pagamento ou entrega.</p><a href="/" target="_blank" rel="noreferrer">Sistema operacional existente ↗</a></footer>
   </div>
  </main>
 </div>;
}
